name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
      - name: 'Typecheck the libraries'
        run: nix develop --command make build
      - name: 'Build the examples'
        run: nix develop --command make examples
      - name: 'Run the tests'
        run: nix develop --command make check
